# Generated by Django 5.1.3 on 2024-12-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tickettype_alter_ticket_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
