# Generated by Django 5.1.3 on 2024-12-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_tickettype_name'),
    ]

    operations = [
    ]
