# Generated by Django 5.1.3 on 2024-12-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_registration_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='comments',
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
